version: '3.8'

services:
  web:
    container_name: epsiburada
    image: epsiburada
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./db.sqlite3:/epsiburada/db.sqlite3
    ports:
      - '8000:8000'
    environment:
      - DEBUG=0

volumes:
  sqlite_data:
