# Generated by Django 5.1.1 on 2024-10-09 07:44

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsimage',
            name='image',
            field=models.ImageField(upload_to=product.models.upload_to_product_slug),
        ),
    ]
